#!/bin/bash 

pip install -r /usr/share/samplesite/requirements.txt

if [ -f /etc/systemd/system/samplesite.service ]; then
    # Reload systemd and enable the service
    sudo systemctl daemon-reload
    sudo systemctl enable samplesite.service
    sudo systemctl start samplesite.service
fi


exit 0
